name: willshex_triangles
description: A port of triangles to dart and flutter
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  willshex_draw:
    path: ./packages/willshex_draw
  go_router: ^11.1.4
  shared_preferences: ^2.2.2
  willshex:
    path: ../willshex-dart
  logging: ^1.2.0
  http: ^1.1.0
  blend_composites:
    path: ../blend_composites
  image: ^4.1.3
  image_blend_composites:
    path: ../image_blend_composites
  url_launcher: ^6.3.2
  google_fonts: ^6.3.3
  subtle_backgrounds:
    path: ./packages/subtle_backgrounds
  fs_shim: ^2.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/monaco/
    - assets/samples/
